# Generated by Django 4.2.1 on 2023-08-13 20:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_userfollowing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_followers",
            new_name="follower",
        ),
        migrations.RenameField(
            model_name="userfollowing",
            old_name="user_followings",
            new_name="user",
        ),
    ]
