# Generated by Django 4.2.1 on 2023-08-14 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_rename_user_followers_userfollowing_follower_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userfollowing",
            old_name="follower",
            new_name="following_user",
        ),
    ]
